### PR TITLE
Refactored Grabbags to include a runner class that encapsulates successes, failures, and not_a_bag

### PR DESCRIPTION
**Pull request by henryborchers**

### CODE REVIEW

**Comment by henryborchers** [comment]
This should have exactly no changes in terms of the functionality. The code, on the other hand, should be much easier to maintain.

**Comment by henryborchers** [comment]
@jfarbowitz @milothiesen Any chance you could check out this PR and try it out? 

This has one of the missing parts I need to make the GUI report the correct results after running a bagging process more than once. Otherwise the the application would have to be restarted between each job to correctly report the number of bags were successful.

**Comment by henryborchers** [comment]
Anybody we should add to review this code?

**Comment by jfarbowitz** [comment]
Not that i can think of other than me and Milo

Jonathan

**Comment by henryborchers** [comment]
@jfarbowitz Check out the pull request and give it a try on your own materials.

**Pull request merged**
