### PR TITLE
Add GPLv3 license

### PR DESCRIPTION
**Pull request by jfarbowitz**
I think we should should go with this license

### CODE REVIEW

**Comment by henryborchers** [comment]
Looks good to me. @jfarbowitz, can you also add the license type to the license field in the setup.py?

**Comment by jfarbowitz** [comment]
@nkrabben @helyxchase Any thoughts on the license?

**Review by henryborchers — CHANGES_REQUESTED** [review]
@jfarbowitz Change license="" to license="GPLv3" in setup.py and I'll merge the changes. Reason, this will store the license metadata when the package is installed.

**Comment by jfarbowitz** [comment]
> @jfarbowitz Change license="" to license="GPLv3" in setup.py and I'll merge the changes. Reason, this will store the license metadata when the package is installed.

Done. You can squash and merge

**Review by henryborchers — APPROVED** [review]

**Comment by henryborchers** [comment]
Done

**Pull request merged**
